// Generated by gencpp from file perception_msgs/ts_Geometry.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_TS_GEOMETRY_H
#define PERCEPTION_MSGS_MESSAGE_TS_GEOMETRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception_msgs
{
template <class ContainerAllocator>
struct ts_Geometry_
{
  typedef ts_Geometry_<ContainerAllocator> Type;

  ts_Geometry_()
    : length(0.0)
    , width(0.0)
    , height(0.0)  {
    }
  ts_Geometry_(const ContainerAllocator& _alloc)
    : length(0.0)
    , width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef double _length_type;
  _length_type length;

   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::perception_msgs::ts_Geometry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::ts_Geometry_<ContainerAllocator> const> ConstPtr;

}; // struct ts_Geometry_

typedef ::perception_msgs::ts_Geometry_<std::allocator<void> > ts_Geometry;

typedef boost::shared_ptr< ::perception_msgs::ts_Geometry > ts_GeometryPtr;
typedef boost::shared_ptr< ::perception_msgs::ts_Geometry const> ts_GeometryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::ts_Geometry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::ts_Geometry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception_msgs::ts_Geometry_<ContainerAllocator1> & lhs, const ::perception_msgs::ts_Geometry_<ContainerAllocator2> & rhs)
{
  return lhs.length == rhs.length &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception_msgs::ts_Geometry_<ContainerAllocator1> & lhs, const ::perception_msgs::ts_Geometry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::ts_Geometry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::ts_Geometry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::ts_Geometry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::ts_Geometry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::ts_Geometry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::ts_Geometry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::ts_Geometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95f1c31b94fb56f33a669e4bf805939a";
  }

  static const char* value(const ::perception_msgs::ts_Geometry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95f1c31b94fb56f3ULL;
  static const uint64_t static_value2 = 0x3a669e4bf805939aULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::ts_Geometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/ts_Geometry";
  }

  static const char* value(const ::perception_msgs::ts_Geometry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::ts_Geometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 length\n"
"float64 width\n"
"float64 height\n"
;
  }

  static const char* value(const ::perception_msgs::ts_Geometry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::ts_Geometry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ts_Geometry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::ts_Geometry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::ts_Geometry_<ContainerAllocator>& v)
  {
    s << indent << "length: ";
    Printer<double>::stream(s, indent + "  ", v.length);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_TS_GEOMETRY_H
